theme: jekyll-theme-minimal
# baseurl: /lecture-slides

title: [Shane's Lectures]
description: [On food technology and philosophy]

markdown: GFM

google_analytics: [UA-179248620-1]
plugins:
  - jemoji
