theme: jekyll-theme-minimal

title: [Lectures]
description: [on topics related to the technology and philosophy 
of food.

[I'm an inline-style link with title](https://www.google.com "Google's Homepage")
]

plugins:
  - jemoji
